In [1]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import re
import nltk
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.svm import SVC
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
df = pd.read_csv('Restaurant_Reviews (2).tsv',sep='\t')
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

# DATA VISUALIZATION



In [5]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [6]:
df.tail()

Review  Liked
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

In [7]:
df.describe()

Liked
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [8]:
df.sample(10)

Review  Liked
884  On three different occasions I asked for well ...      0
696  We had so much to say about the place before w...      0
111  At least 40min passed in between us ordering a...      0
617  Despite how hard I rate businesses, its actual...      0
740  The restaurant is very clean and has a family ...      1
97                               Food arrived quickly!      1
945  The chipolte ranch dipping sause was tasteless...      0
144  Nice blanket of moz over top but i feel like t...      1
297  I love the fact that everything on their menu ...      1
627  Any grandmother can make a roasted chicken bet...      0

In [9]:
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [11]:
df1 = df.copy()
df1

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [12]:
# COUNT OF LIKES 1

df_1_count = df[df['Liked']==1].count()
df_1_count

Review    500
Liked     500
dtype: int64

In [13]:
# COUNT OF dISLIKES 0

df_0_count = df[df['Liked']==0].count()
df_0_count

Review    500
Liked     500
dtype: int64

# CLEANING THE TEXT

In [14]:
corpus = []
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]', ' ', df['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)
print(corpus)
    

['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would not go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place not worth time let alon vega', 'not like', 'burritto blah', 'food not amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could

# APPLYING THE BAG OF WORDS(BOG) MODEL

In [15]:
# The bag-of-words model is a way of representing text data when modeling text with machine learning algorithms.
# The bag-of-words model is simple to understand and implement and has seen great success in problems such as 
# language modeling and document Classification.

In [16]:
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, -1].values

# SPLITTING THE DATASET INTO TRAINING SET AND TEST SET

In [17]:
# Train test Split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state = 42)


In [18]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [19]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [20]:
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print("Accuracy Score=",accuracy_score(y_test,y_pred1))
print("Confusion Matrix=",confusion_matrix(y_test,y_pred1))
print("Precision Score=",precision_score(y_test,y_pred1))

Accuracy Score= 0.6727272727272727
Confusion Matrix= [[ 90  83]
 [ 25 132]]
Precision Score= 0.6139534883720931


In [21]:
mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print("Accuracy Score=",accuracy_score(y_test,y_pred2))
print("Confusion Matrix=",confusion_matrix(y_test,y_pred2))
print("precission Score=",precision_score(y_test,y_pred2))

Accuracy Score= 0.7727272727272727
Confusion Matrix= [[135  38]
 [ 37 120]]
precission Score= 0.759493670886076


In [22]:
bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print("Accuracy Score=",accuracy_score(y_test,y_pred3))
print("Confusion Matrix=",confusion_matrix(y_test,y_pred3))
print("precission Score=",precision_score(y_test,y_pred3))

Accuracy Score= 0.7696969696969697
Confusion Matrix= [[129  44]
 [ 32 125]]
precission Score= 0.7396449704142012


# Applying Tfidf

In [23]:
tfidf = TfidfVectorizer()

In [24]:
X = tfidf.fit_transform(df['Review']).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
# Train Test Split

from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state = 42)

In [27]:
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print("Accuracy Score=",accuracy_score(y_test,y_pred1))
print("Confusion Matrix=",confusion_matrix(y_test,y_pred1))
print("Precission Score=",precision_score(y_test,y_pred1))

Accuracy Score= 0.696969696969697
Confusion Matrix= [[105  68]
 [ 32 125]]
Precission Score= 0.6476683937823834


In [28]:
mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print("Accuracy Score=",accuracy_score(y_test,y_pred2))
print("Confusion Matrix=",confusion_matrix(y_test,y_pred2))
print("Precission Score=",precision_score(y_test,y_pred2))

Accuracy Score= 0.8121212121212121
Confusion Matrix= [[138  35]
 [ 27 130]]
Precission Score= 0.7878787878787878


In [29]:
bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print("Accuracy Score=",accuracy_score(y_test,y_pred3))
print("Confusion Matrix=",confusion_matrix(y_test,y_pred3))
print("Precission Score=",precision_score(y_test,y_pred3))

Accuracy Score= 0.7212121212121212
Confusion Matrix= [[110  63]
 [ 29 128]]
Precission Score= 0.6701570680628273


# Applying Logistic Regression

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state = 42)

In [32]:
lr_model = LogisticRegression()
lr_model.fit(X_train,y_train)

LogisticRegression()

In [34]:
predictions = lr_model.predict(X_test)
print(metrics.confusion_matrix(y_test,predictions))

[[138  35]
 [ 30 127]]


In [35]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81       173
           1       0.78      0.81      0.80       157

    accuracy                           0.80       330
   macro avg       0.80      0.80      0.80       330
weighted avg       0.80      0.80      0.80       330



In [36]:
print(metrics.accuracy_score(y_test,predictions))

0.803030303030303


# Support Vector Classification (SVC)

In [39]:
svc_model = SVC()
svc_model.fit(X_train,y_train)

SVC()

In [41]:
predictions = svc_model.predict(X_test)
print(metrics.confusion_matrix(y_test,predictions))

[[147  26]
 [ 31 126]]


In [42]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       173
           1       0.83      0.80      0.82       157

    accuracy                           0.83       330
   macro avg       0.83      0.83      0.83       330
weighted avg       0.83      0.83      0.83       330



In [43]:
print(metrics.accuracy_score(y_test,predictions))

0.8272727272727273


# Hence the accuracy of SVC model is better than other models, so we will select SVC model.